{{- if .Values.gcloud.configconnector -}}
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
  app.kubernetes.io/managed-by: Helm
spec:
  mode: cluster
  googleServiceAccount: "{{ .Values.gcloud.serviceaccount.email }}"
{{- end -}}