{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Values.namespace.name }}
    annotations:
        cnrm.cloud.google.com/project-id: {{ $.Values.gcloud.project }}
    labels:
        name: {{ .Values.namespace.name }}
{{- end -}}